const { withDangerousMod, withProjectBuildGradle } = require('expo/config-plugins');
const fs = require('node:fs');
const path = require('node:path');

/**
 * Everything the Android build needs that `expo prebuild` does not generate and
 * `prebuild --clean` deletes:
 *
 *   android/build.gradle                          ndkPath -> a space-free NDK
 *   android/build.gradle                          a working generateStubPCH
 *   android/local.properties                      sdk.dir -> a space-free SDK
 *   android/gradle/gradle-daemon-jvm.properties   toolchainVersion=17
 *
 * All of it exists because the Windows username contains a space. Full diagnosis
 * is in README.md; the short version:
 *
 *  - CMake shortens spaced paths to 8.3 form and the NDK passes
 *    -no-canonical-prefixes, so clang cannot find its own lib directory and
 *    links without libc++ — every C++ module dies on `std::__ndk1::` symbols.
 *
 *  - Gradle 9 reads the daemon JVM criteria above org.gradle.java.home, and
 *    ~/.gradle/gradle.properties on this machine pins Android Studio's JBR
 *    (JDK 25) for the old Capacitor app. JDK 24+ writes a restricted-method
 *    warning to stderr, and AGP's prefab step treats any stderr line as a build
 *    error — so configureCMakeDebug fails before it starts. Pinning 17 here also
 *    fixes Android Studio builds without touching that global file.
 *
 *  - expo-modules-core's generateStubPCH task splits its clang command on every
 *    space, so the quoted paths under "Shamim Hasan" reach clang in fragments.
 *    It runs during Gradle sync, which makes Android Studio unusable while the
 *    command line builds fine.
 *
 * `sdk.dir` alone is not enough, and that is the part worth knowing: Android
 * Studio rewrites local.properties with its own SDK Location on every Gradle
 * sync, so a corrected sdk.dir survives exactly until the next sync and the
 * linker errors come straight back. Pinning `ndkPath` in build.gradle is what
 * makes the fix durable — verified by building `:react-native-worklets` to
 * completion with the spaced sdk.dir deliberately left in place.
 *
 * These files are easy to write by hand and just as easy to lose. Generating
 * them from the prebuild itself is what makes them stay.
 */

const SDK_CANDIDATES = [
  process.env.ANDROID_SDK_NO_SPACES,
  'C:/AndroidSdk',
  process.env.ANDROID_HOME,
  process.env.ANDROID_SDK_ROOT,
];

// Gradle parses this as a Java properties value: backslashes and the drive-letter
// colon are escaped ("C:\AndroidSdk" -> "C\:\\AndroidSdk").
const asPropertiesPath = (p) =>
  p.replace(/\//g, '\\').replace(/\\/g, '\\\\').replace(/:/g, '\\:');

function resolveSdk() {
  const found = SDK_CANDIDATES.filter(Boolean).find((p) => fs.existsSync(p));
  if (!found) return { error: 'no Android SDK found' };
  if (/\s/.test(found)) {
    return {
      error:
        `the only SDK path found contains a space (${found}); C++ modules will fail to link.\n` +
        '  Create a junction once, then re-run prebuild:\n' +
        '  New-Item -ItemType Junction -Path C:\\AndroidSdk -Target "$env:LOCALAPPDATA\\Android\\Sdk"',
    };
  }
  return { sdk: found };
}

const NDK_PIN_MARKER = '// [android-build-env] space-free NDK';

/**
 * Pins `ndkPath` on every Android module in the build.
 *
 * It has to be every module, not just `:app` — the module that actually failed
 * to link was `:react-native-worklets`, and each native library resolves its own
 * NDK. `allprojects { plugins.withId('com.android.base') }` catches them all,
 * including ones added by a future dependency.
 *
 * Position in the file matters, and getting it wrong fails loudly:
 * `expo-root-project` and `com.facebook.react.rootproject` evaluate subprojects
 * as they are applied, so a block appended after those `apply plugin:` lines
 * runs against projects AGP has already configured and Gradle rejects it with
 * "It is too late to set ndkPath. It has already been read to configure this
 * project." Hence the insertion before the first `apply plugin:` line rather
 * than a simple append.
 */
const ndkPinBlock = (sdk) => `
${NDK_PIN_MARKER} — generated by plugins/withAndroidBuildEnv.js. Edit the plugin, not this file.
//
// CMake shortens a spaced path to 8.3 form and the NDK toolchain passes
// -no-canonical-prefixes, so with the SDK under "C:\\Users\\<name with space>\\..."
// clang cannot resolve its own executable path, fails to find its lib directory
// and links without libc++ — hundreds of "undefined symbol: std::__ndk1::..."
// errors out of ld.lld. Correcting sdk.dir fixes it too, but Android Studio
// rewrites local.properties on every Gradle sync; this survives that.
allprojects {
  plugins.withId('com.android.base') {
    def ndkRoot = new File('${sdk.replace(/\\/g, '/')}', 'ndk')
    def wanted = rootProject.ext.has('ndkVersion') ? rootProject.ext.ndkVersion as String : null
    def pinned = wanted != null ? new File(ndkRoot, wanted) : null
    // No pinned version (or it is not installed under the space-free path):
    // fall back to the newest NDK there, so an NDK upgrade does not break this.
    if (pinned == null || !pinned.isDirectory()) {
      def installed = ndkRoot.isDirectory()
        ? (ndkRoot.listFiles({ File f -> f.isDirectory() } as FileFilter) ?: []).sort { it.name }
        : []
      pinned = installed.isEmpty() ? null : installed.last()
    }
    if (pinned != null) {
      android.ndkPath = pinned.absolutePath
    }
  }
}
`;

const withSpaceFreeNdk = (config) =>
  withProjectBuildGradle(config, (cfg) => {
    const { sdk, error } = resolveSdk();
    if (!sdk) {
      console.warn(`[android-build-env] skipped ndkPath pin — ${error}`);
      return cfg;
    }
    if (cfg.modResults.language !== 'groovy') {
      throw new Error('withAndroidBuildEnv: expected a Groovy android/build.gradle');
    }
    if (cfg.modResults.contents.includes(NDK_PIN_MARKER)) return cfg;

    // Must land before the root project's plugins are applied — see above.
    const anchor = /^apply plugin:/m;
    if (!anchor.test(cfg.modResults.contents)) {
      throw new Error(
        'withAndroidBuildEnv: no `apply plugin:` line in android/build.gradle to ' +
          'insert the ndkPath pin before. Appending it instead would fail the build ' +
          'with "It is too late to set ndkPath", so this stops here rather than ' +
          'producing a project that cannot link.'
      );
    }
    cfg.modResults.contents = cfg.modResults.contents.replace(
      anchor,
      `${ndkPinBlock(sdk)}\n$&`
    );
    console.log(`[android-build-env] build.gradle ndkPath -> ${sdk}/ndk/<version>`);
    return cfg;
  });

const STUB_PCH_MARKER = '// [android-build-env] stub PCH argv';

/**
 * Replaces the body of expo-modules-core's `generateStubPCH` task.
 *
 * That task is an IDE helper: it pre-creates a throwaway precompiled header so
 * Android Studio's C++ engine has one to read during sync, then backdates it so
 * ninja rebuilds the real one on the next build. It assembles the clang command
 * with `entry.command.split(" ")`, and every path in compile_commands.json here
 * sits under "Shamim Hasan" — so quoted arguments are torn in half, and the two
 * regexes that swap in the stub header stop at the space and match from the
 * wrong offset. clang gets handed the wreckage and sync dies on it.
 *
 * It is hooked into `prepareKotlinBuildScriptModel`, i.e. the first thing a
 * Gradle sync runs, so nothing else in the project gets a chance to configure.
 * Builds are unaffected, which is why `expo run:android` never noticed.
 *
 * Overriding from the root project rather than patching node_modules keeps the
 * fix alive across `npm install`, and regenerating it here keeps it alive across
 * `prebuild --clean` — the same reason the ndkPath pin lives here.
 */
const stubPchFixBlock = () => `
${STUB_PCH_MARKER} — generated by plugins/withAndroidBuildEnv.js. Edit the plugin, not this file.
//
// expo-modules-core builds this task's clang command by splitting the entry from
// compile_commands.json on every space, and finds the paths to rewrite with a
// no-whitespace regex. Both assume no path contains a space. Under
// "C:/Users/Shamim Hasan/..." they produce:
//
//   clang++: error: no such file or directory: 'C:/Users/Shamim C:/Users/Shamim Hasan/.../stub_pch.hxx'
//   clang++: error: no input files
//
// Same behaviour as upstream, minus the two assumptions: split the command the
// way a shell would, and swap whole argv entries instead of rewriting the
// command string.
allprojects { proj ->
  proj.tasks.matching { it.name == 'generateStubPCH' }.configureEach { stubTask ->
    def cxxDir = proj.file('.cxx')
    stubTask.actions.clear()
    stubTask.doLast {
      if (!cxxDir.exists()) {
        return
      }

      // A quoted run keeps its spaces and loses its quotes, so
      // -I"C:/Users/Shamim Hasan/..." arrives at clang as one argument.
      def tokenize = { String line ->
        def argv = []
        def arg = new StringBuilder()
        boolean quoted = false
        boolean started = false
        for (int i = 0; i < line.length(); i++) {
          String ch = line.substring(i, i + 1)
          if (ch == '"') {
            quoted = !quoted
            started = true
          } else if (ch == ' ' && !quoted) {
            if (started) {
              argv.add(arg.toString())
              arg.setLength(0)
              started = false
            }
          } else {
            arg.append(ch)
            started = true
          }
        }
        if (started) {
          argv.add(arg.toString())
        }
        return argv
      }

      cxxDir.eachFileRecurse { file ->
        if (file.name != 'compile_commands.json') {
          return
        }

        new groovy.json.JsonSlurper().parseText(file.text).each { entry ->
          if (!entry.file.endsWith('cmake_pch.hxx.cxx')) {
            return
          }

          def pchFile = new File(entry.file.substring(0, entry.file.length() - '.cxx'.length()) + '.pch')

          if (!pchFile.exists() || pchFile.length() == 0) {
            def stubHeader = new File(entry.directory, 'stub_pch.hxx')
            stubHeader.text = ''
            def stubHeaderPath = stubHeader.absolutePath.replace('\\\\', '/')

            // The forced include (-Xclang <path>/cmake_pch.hxx) and the source
            // operand (<path>/cmake_pch.hxx.cxx) are each a whole argv entry
            // once the command is tokenised, so they match exactly.
            def argv = tokenize(entry.command).collect { String a ->
              def normalised = a.replace('\\\\', '/')
              if (normalised.endsWith('cmake_pch.hxx.cxx') || normalised.endsWith('cmake_pch.hxx')) {
                return stubHeaderPath
              }
              return a
            }

            def process = new ProcessBuilder(argv)
              .directory(new File(entry.directory))
              .redirectErrorStream(true)
              .start()
            // Drained before waitFor: redirectErrorStream means one pipe for both
            // streams, and a full pipe buffer would deadlock the wait.
            def output = process.inputStream.text
            if (process.waitFor() != 0) {
              throw new GradleException('Stub PCH generation failed: ' + output)
            }
          }

          // Ensure PCH is older than source so ninja rebuilds the real one during build
          pchFile.setLastModified(new File(entry.file).lastModified() - 1)
        }
      }
    }
  }
}
`;

const withStubPchArgvFix = (config) =>
  withProjectBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error('withAndroidBuildEnv: expected a Groovy android/build.gradle');
    }
    if (cfg.modResults.contents.includes(STUB_PCH_MARKER)) return cfg;

    // Same anchor as the ndkPath pin: the override has to be registered before
    // the root plugins start evaluating subprojects, or expo-modules-core is
    // already configured by the time `allprojects` reaches it.
    const anchor = /^apply plugin:/m;
    if (!anchor.test(cfg.modResults.contents)) {
      throw new Error(
        'withAndroidBuildEnv: no `apply plugin:` line in android/build.gradle to ' +
          'insert the generateStubPCH override before. Without it every Gradle ' +
          'sync fails on :expo-modules-core:generateStubPCH.'
      );
    }
    cfg.modResults.contents = cfg.modResults.contents.replace(anchor, `${stubPchFixBlock()}\n$&`);
    console.log('[android-build-env] build.gradle generateStubPCH -> space-safe argv');
    return cfg;
  });

const withBuildEnvFiles = (config, { toolchainVersion = 17 } = {}) =>
  withDangerousMod(config, [
    'android',
    (cfg) => {
      const androidDir = cfg.modRequest.platformProjectRoot;

      const { sdk, error } = resolveSdk();
      if (sdk) {
        fs.writeFileSync(
          path.join(androidDir, 'local.properties'),
          '# Generated by plugins/withAndroidBuildEnv.js on every prebuild.\n' +
            '# Must stay space-free — see README.md. Edit the plugin, not this file.\n' +
            `sdk.dir=${asPropertiesPath(sdk)}\n`
        );
        console.log(`[android-build-env] local.properties sdk.dir -> ${sdk}`);
      } else {
        // Not fatal: ANDROID_HOME may still be correct on another machine, and
        // failing prebuild over it would block anyone who does not need the fix.
        console.warn(`[android-build-env] skipped local.properties — ${error}`);
      }

      const gradleDir = path.join(androidDir, 'gradle');
      fs.mkdirSync(gradleDir, { recursive: true });
      fs.writeFileSync(
        path.join(gradleDir, 'gradle-daemon-jvm.properties'),
        '# Generated by plugins/withAndroidBuildEnv.js on every prebuild.\n' +
          '# Must stay <= 21: JDK 24+ writes a restricted-method warning to stderr and\n' +
          "# AGP's prefab step treats stderr as build errors. See the Android build notes in README.md.\n" +
          `toolchainVersion=${toolchainVersion}\n`
      );
      console.log(`[android-build-env] gradle-daemon-jvm.properties toolchainVersion=${toolchainVersion}`);

      return cfg;
    },
  ]);

const withAndroidBuildEnv = (config, options = {}) =>
  withStubPchArgvFix(withSpaceFreeNdk(withBuildEnvFiles(config, options)));

module.exports = withAndroidBuildEnv;
